/**
 * list of all client or tunnel error codes with their corresponding text to show.
 * client error occurred when the connection has established but we have received an error instruction via web-socket.
 *  errors other than client errors are tunnel errors.
 */
export const clientOrTunnelErrors = {
  'default': `clientOrTunnelErrorsDefault`,
  '0x0201': `The remote server has rejected this connection attempt because there are too many active connections. Please wait a few minutes and try again.`,
  '0x0202': `The connection has been closed because the server is taking too long to respond. Please try again or contact your system administrator.`,
  '0x0203': `The server encountered an error and has closed the connection. Please try again or contact your system administrator.`,
  '0x0204': `The requested connection (application) does not exist. Please check the connection name and try again.`,
  '0x0205': `This connection is currently in use, and concurrent access to this connection is not allowed. Please try again later.`,
  '0x0206': `Remote machine or connection's IP address is not available.`,
  '0x0207': `The remote server is currently unreachable. If the problem persists, please notify your system administrator, or check your system logs.`,
  '0x0208': `The remote server is currently unreachable. If the problem persists, please notify your system administrator, or check your system logs.`,
  '0x0209': `RDP Session Conflict. Someone else connected to this machine.`,
  '0x020A': `The remote server has closed the connection because it appeared to be inactive. If this is undesired or unexpected, please notify your system administrator, or check your system settings.`,
  '0x020B': `The remote server has forcibly closed the connection. If this is undesired or unexpected, please notify your system administrator`,
  '0x0220': `Mismatch of remote-machine's secure connection parameters (ssl)`,
  '0x0221': `Error in authenticate the validity of remote machine's key`,
  '0x0222': `Mismatch of secure connection parameter (ssl, tls)`,
  '0x0223': `Error in establishing secure connection (ssl, tls)`,
  '0x0224': `Establishing connection was denied by remote-machine`,
  '0x0225': `Remote-machine is not available`,
  '0x0226': `Error in authenticating the validity of remote-machine's certificate`,
  '0x0227': `Based on configured admin policy, self-signed certificates are not acceptable. Please contact your system administrator.`,
  '0x0300': `The operation could not be performed because bad parameters were given.`,
  '0x0301': `The remote-machine's username/password is not correct. Please try again with correct username/password.`,
  '0x0303': `You do not have permission to access this connection. If you require access, please ask your system administrator to add you the list of allowed users.`,
  '0x0304': `User's saved password's id is invalid.`,
  '0x0305': `Your access to this connection has been restricted`,
  '0x0306': `Timeout occurred because of being idle for a long time`,
  '0x0307': `Connection is terminated because of entering a forbidden command`,
  '0x0308': `The remote server has closed the connection because there has been no response from your browser for long enough that it appeared to be disconnected. This is commonly caused by network problems, such as spotty wireless signal, or simply very slow network speeds. Please check your network and try again.`,
  '0x031D': `The remote server is denying access to this connection because you have exhausted the limit for simultaneous connection use by an individual user. Please close one or more connections and try again.`,
  '0x036C': `Error in connecting to Wina's agent in remote system`,
  '0x04A0': `Connection is terminated via Wina admin`,
  '0x04A1': `Connection is terminated because of permission denial.`,
  '0x04A2': `Connection is not established because of permission denial.`,
  '0x04A3': `Connection is not established because the user has been locked in this connection due to too many failed attempts.`,
  '0x04A4': `Wina license is not available`,
  '0x04A5': `Wina license has been expired`,
  '0x04A6': `The number of simultaneous active connections has exceeded the allowable limit`,
  '0x04A7': `Wina license is invalid`,
  '0x04A8': `Wina license is invalid`,
};
